### ISSUE TITLE
Write template requirements on the documentation

### ISSUE THREAD

**Issue by Naokimi** [Naokimi/lewagon-rails-template-plus#26]
Found from https://github.com/Naokimi/lewagon-rails-template-plus/issues/25

Need to update the Readme to list the requirements to successfully use the template. Since most users normally came from Le Wagon's bootcamp and setup their dev environment using [their guide](https://github.com/lewagon/setup), it can be a good guide to check which items need to be listed.

**Comment by digracesion** [comment]
i would like to work on this! 🙇‍♀️

**Comment by Naokimi** [comment]
@digracesion thank you 🙏
